import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-blue-600 text-white  p-5 flex gap-5">
          <Link href="/">Home</Link>
          <Link href="/dashboard">Dashboard</Link>
          <Link href="/dashboard/customers">Customer</Link>
          <Link href="/settings">Settings</Link>
          <Link href="/Ai.team">Team</Link>
          <Link href="/blog" target="blank">
            Blog
          </Link>
          <Link href="/login">Log in</Link>
        </header>
        {children}
        <footer className=" bg-blue-700 text-white p-5 my-72">
          This is footer
        </footer>
      </body>
    </html>
  );
}
